### ISSUE TITLE
"mksqlite"  missing 

### ISSUE THREAD

**Issue by marselomeri** [Airspace-Encounter-Models/em-core#14]
Hello, 

is the mksqlite still required? I cannot find it at the suggested directory em-core\matlab\utilities-3rdparty\mksqlite. 

Thanks

**Comment by aweinert-MIT** [comment]
It is provided as a git submodule and defined in the [`.gitmodules`](https://github.com/Airspace-Encounter-Models/em-core/blob/master/.gitmodules) file. Have you tried initializing the git submodules?

P.S. `mksqlite` is only used in a few places in `em-core` and we're considering changing it from a required setup to an optional component.

**Comment by marselomeri** [comment]
Thanks, it works now!
