### ISSUE TITLE
[BUG] FAA registry format change

### ISSUE THREAD

**Issue by aadeabreu** [Airspace-Encounter-Models/em-core#4]
FAA seems to have added new columns in the aircraft reference file causing issues while running /matlab/utilities-1stparty/RUN_readfaaacreg.m

/matlab/utilities-1stparty/aircraftregistry/readfaaacreg.m needs to be updated to read new format (as of 07/2021)

**Comment by aweinert-MIT** [comment]
The [Download Documentation (PDF)](https://www.faa.gov/licenses_certificates/aircraft_certification/aircraft_registry/media/ardata.pdf) for file content and configuration of the aircraft registration master file was last updated on 12/03/2020. I compared the most recent version to the older version of the documentation dated 3/26/2019. I identified two additional fields at to the aircraft reference file, which includes the record length to 158 characters from 89 characters. From the 12/3/2020 documentation, the two new elements are the following:

| Element  | Position Location in Record | Number of Positions | Descriptions
| ------------- | ------------- | ------------- | ------------- |
| TC Data Sheet | 90 - 105 | 15 | Type Certificate Data Sheet
| TC Data Holder | 107 - 157 | 50 | Type Certificate Data Holder

Commit 016158a by @aadeabreu appropriately the `textscan` in `readfaaacreg` to scan fields of length 15 and 50.
